server:
  port: 8000



spring:
  application:
    name: MyNotesApp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
